### PR TITLE
new:irregular inflection of prefix verbs with known base

### PR DESCRIPTION
**Pull request by JakobSteixner**
Fix implementing logic to correctly identify the (irregular) base of prefixed verbs.
Old: 

    >>> conjugate('gehen', (de.PAST, 2, de.SINGULAR)) 
    'gingst' # correct
    >>> conjugate('vorgehen', (de.PAST, 2, de.SINGULAR))
    'gehtest vor' # incorrect

Explanation: since 'vorgehen' is not found in the lexicon, a default regular inflection strategy applies. Even though the separable prefix is correctly identified, the base form thus extracted isn't checked against the lexicon and the available information about its irregular inflection thus lost.

New:

    >>> conjugate('gehen', (de.PAST, 2, de.SINGULAR)) 
    'gingst' # correct
    >>> conjugate('vorgehen', (de.PAST, 2, de.SINGULAR))
    'gingst vor' # correct

This fix is achieved with a second pass to `lemma` after stripping the prefix, to identify the known irregular inflection of the base form 'gehen'.

Further, blacklists of verbs that look like they might be prefix verbs or latinate verbs with the suffix 'ier(en)'  have been included to block the parser's exceptional treatment of those.

### CODE REVIEW

**Comment by JakobSteixner** [comment]
- additional bug fixes
- 3.7 compatibility (new behavior of `StopIteration`)
- additional checks for rule-based verb conjugatio: blacklists of verbs that look like prefix verbs or latinate verbs with the '-ieren' suffix but don't share their special behavior

**Comment by JakobSteixner** [comment]
@thalelinh `test_web.TestSearchEngine.test_search_twitter` failing under 2.7

**Comment by thalelinh** [comment]
Which tests?

**Comment by JakobSteixner** [comment]
> Which tests?

test_web.py, `TestSearchEngine.test_search_twitter` -- L503 with 0 results (1 expected), maybe an API limit issue?

**Comment by thalelinh** [comment]
> > Which tests?
> 
> test_web.py, `TestSearchEngine.test_search_twitter` -- L503 with 0 results (1 expected), maybe an API limit issue? Nothing either of us touched, I'm skipping it for now.
> 
> log: https://travis-ci.org/clips/pattern/builds/514015081?utm_source=github_status&utm_medium=notification

Yeah, I [made a retry loop](https://github.com/clips/pattern/pull/264/files#diff-f7b94985b962829d535a449babfb98d3) on my PR (which focused on fixing the CI). It worked there, not the best solution though :sweat_smile:

**Comment by thalelinh** [comment]
My guess now is that there's a `seed(0)` missing after [_test_classifier instantiate a Classifier](https://github.com/clips/pattern/blob/5b85d998c30ddc6772b56310713530224466083a/test/test_vector.py#L891), during the `test_slp`.
If you look at [`shuffled` definition](https://github.com/clips/pattern/blob/5b85d998c30ddc6772b56310713530224466083a/pattern/vector/__init__.py#L106), which is called without the seed param at [SLP constructor](https://github.com/clips/pattern/blob/5b85d998c30ddc6772b56310713530224466083a/pattern/vector/__init__.py#L3025), you will see that it calls `seed(None)`, which is equivalent of `seed(time.now)`, that we obviously don't want to happen in a test case. :smile:

**Comment by thalelinh** [comment]
The Twitter test error was actually just causality. It's a query using a given string, sometimes there aren't any results.

**Comment by JakobSteixner** [comment]
> The Twitter test error was actually just causality. It's a query using a given string, sometimes there aren't any results.

I thought so. Now failing with a version conflict in pytest setup though...

**Comment by JakobSteixner** [comment]
Appears to pass now!

**Pull request merged**
