### PR TITLE
Chink->Chonk

### PR DESCRIPTION
**Pull request by zfaizal**
Modified all files with 'Chink', 'chink', 'CHINK' to all forms of 'chonk'.

### CODE REVIEW

**Comment by LynnCo** [comment]
reference #111

**Comment by kinow** [comment]
@zfaizal I think your pull request includes some temporary files (ending with ~) as well?

**Comment by zfaizal** [comment]
Thank, Any idea why that happened?

**Comment by tartillo** [comment]
add a line to `.gitignore`:
`*~`

**Pull request closed without merging**
