### PR TITLE
Fix #140:Pattern 2.6 not Python 3 compatible

### LINKED ISSUE #140: Pattern 2.6 not Python 3 compatible
Hello

I got this error when installing with Python 3.5:

``` bash
Downloading/unpacking pattern (from -r requirements.txt (line 6))
  Downloading pattern-2.6.zip (24.6MB): 24.6MB downloaded
  Running setup.py (path:/tmp/pip-build-c80fr52l/pattern/setup.py) egg_info for package pattern
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-c80fr52l/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-c80fr52l/pattern/setup.py", line 40

    print n

          ^

SyntaxError: Missing parentheses in call to 'print'
```

### PR DESCRIPTION
**Pull request by abhijeetchauhan**
There was a syntax error in print.Due to recent changes in python3.
Reference: https://docs.python.org/3/whatsnew/3.0.html#print-is-a-function

### CODE REVIEW

**Comment by dav009** [comment]
:+1:

**Comment by ExplodingCabbage** [comment]
> recent changes in python3

These aren't recent; Python 3.0 was released 8 years ago.

> Fix #140:Pattern 2.6 not Python 3 compatible

I haven't looked in detail at the efforts to make Pattern compatible with Python 3, but I think much more is needed than this; see https://github.com/clips/pattern/issues/62.

**Comment by abhijeetchauhan** [comment]
You, guys are correct.I tried using 2to3 refractoring tool but many errors were coming up.

**Comment by ExplodingCabbage** [comment]
Perhaps close this PR, then?

**Pull request closed without merging**
